import os

BROKER_URL = os.environ['CLOUDAMQP_URL']
BROKER_POOL_LIMIT = 3
CELERY_RESULT_BACKEND = os.environ['REDISCLOUD_URL']
CELERY_REDIS_MAX_CONNECTIONS = 10
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_EVENT_SERIALIZER = 'json'

